/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import Nav from "@/components/Header/Nav";
import { loadArray } from "@/utils/api";
import styles from "@/styles/SubPage.module.css";

export default function About({ pages }) {
  return (
    <>
      <Head>
        <title>{"Cam's Camera"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="w-auto h-full min-h-screen p-0 m-0 border-0">
          <div className="absolute top-0 w-full bg-cam-gray">
            <img
              className="m-auto w-1/3 max-w-[150px]"
              src="/img/logo3.png"
              alt="cams camera logo"
            />
          <div className={`pt-6 m-0 ${styles.navPos}`}>
            <div className={`w-full m-0 p-0 h-8 ${styles.nav}`}>
              <Nav pages={pages}/>
            </div>
          </div>
          </div>
        </div>
      </main>
    </>
  );
}

export async function getStaticProps() {
  const pages = await loadArray("/api/paths", "paths");
  return { props: { pages: pages } };
}
