import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import 'bootstrap/dist/css/bootstrap.min.css';
import styles from '@/styles/Home.module.css'
import RentalsControl from '@/components/RentalsControl'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <script src="https://cdn.jsdelivr.net/npm/react/umd/react.production.min.js" crossorigin></script>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <RentalsControl />
      </main>
      
    </>
  )
}
