import Head from "next/head";
import Clients from "@/components/Clients";
import Header from "@/components/Header";
import RentalsControl from "@/components/RentalsControl";
import Footer from "@/components/Footer";
import { loadArray } from "@/utils/api";

export default function Home({ pages }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header pages={pages} />
        <Clients />
        <RentalsControl />
        <Footer />
      </main>
    </>
  );
}

export async function getStaticProps() {
  const pages = await loadArray("/api/paths", "paths");
  return { props: { pages: pages } };
}
